services:
  web:
    image: registry.gitlab.com/storyteller-platform/storyteller:latest
    container_name: storyteller
    volumes:
      - ./data:/data:rw
    environment:
      - STORYTELLER_SECRET_KEY_FILE=/run/secrets/secret_key
      - STORYTELLER_LOG_LEVEL=debug
    ports:
      - "8001:8001"
    secrets:
      - secret_key
    restart: unless-stopped

secrets:
  secret_key:
    file: ./STORYTELLER_SECRET_KEY.txt
